### ISSUE TITLE
Question about the code

### ISSUE THREAD

**Issue by CarterLi** [victorstewart/quicperf#6]
```
	void setCallbackData(struct io_uring_sqe *sqe, uint8_t op, void *data)
	{
		sqe->user_data = ((uint64_t)op << 48) | (uint64_t)data;
	}
```

Is it guaranteed being safe to do so?

**Comment by victorstewart** [comment]
yes all 64 bit architectures only use 48 bit addresses. so always 16 free bits.

**Comment by CarterLi** [comment]
> yes all 64 bit architectures only use 48 bit addresses. so always 16 free bits.

Is it Linux specific? Does it apply to Windows / BSD too?

**Comment by victorstewart** [comment]
i only use linux but this blog post from this year states windows only uses 44 bits.

[https://helgeklein.com/blog/windows-x64-all-the-same-yet-very-different-part-3/](https://helgeklein.com/blog/windows-x64-all-the-same-yet-very-different-part-3/)

google is your friend lol

**Comment by victorstewart** [comment]
here's some more reading on the subject as well:

[https://stackoverflow.com/questions/16198700/using-the-extra-16-bits-in-64-bit-pointers/18426582](https://stackoverflow.com/questions/16198700/using-the-extra-16-bits-in-64-bit-pointers/18426582)

**Comment by CarterLi** [comment]
Thanks
